project_id = "imgjhfmtsjvnhgjimndm"

[functions.realtime-session]
verify_jwt = false

[functions.simli-session]
verify_jwt = false

[functions.heygen-token]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.did-stream]
verify_jwt = false
